name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
#          - dockerfile: "Dockerfile"
#            tags: "latest"
#            platforms: "linux/amd64"
          - dockerfile: "Dockerfile"
            tags: "latest-arm64"
            platforms: "linux/arm64"
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build --platform ${{ matrix.platforms }} -f docker/${{ matrix.dockerfile }} .
